
MOUSE_TYPE = 0
KEYBOARD_TYPE = 1

MOUSE_ACTION_MOVE = 0
MOUSE_ACTION_LEFT_DOWN = 1
MOUSE_ACTION_LEFT_UP = 2
MOUSE_ACTION_RIGHT_DOWN = 3
MOUSE_ACTION_RIGHT_UP = 4

KEYBOARD_ACTION_DOWN = 0
KEYBOARD_ACTION_UP = 1
